name: campus-share-app
region: nyc
services:
  - name: backend
    github:
      branch: main
      deploy_on_push: true
      repo: f3r21/campus-share-app
    source_dir: backend
    run_command: node server.js
    http_port: 3001
    routes:
      - path: /api
      - path: /uploads
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${campus-db.DATABASE_URL}
      - key: SPACES_ACCESS_KEY
        scope: RUN_TIME
        value: ""
      - key: SPACES_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: ""
      - key: SPACES_BUCKET_NAME
        scope: RUN_TIME
        value: ""

static_sites:
  - name: frontend
    github:
      branch: main
      deploy_on_push: true
      repo: f3r21/campus-share-app
    source_dir: frontend
    build_command: npm run build
    output_dir: dist
    routes:
      - path: /

databases:
  - name: campus-db
    engine: PG
    version: "16"
    production: false
